version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pub
    directory: /tools/update_version
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
