name: bootstrap_icons
description: Implementation of Bootstrap Icons in Flutter with over 2,000 icons.
version: 1.13.1+2
homepage: https://github.com/ricardodalarme/Bootstrap-Icons-Flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=0.1.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: BootstrapIcons
      fonts:
        - asset: fonts/BootstrapIcons.otf

screenshots:
  - description: "BootstrapIcons hero"
    path: images/icons-hero.png
