name: Auto Tag

on:
  push:
    branches: [main]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: "Auto Tag when the pubspec.yaml version changes"
        uses: jacopocarlini/action-autotag@3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
          tag_prefix: "v"
